version: '3'

services:

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 5173
    depends_on:
      - server
    volumes:
      - ./client:/code
        ./client/node_modules:/code/node_modules

  server:
    build:
      context: /server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./server:/code

  db:
    image: postgres:13.14-alpine3.19
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgre
    ports:
      - "5432:5432"

  
