# Generated by Django 5.0.3 on 2024-05-14 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='date',
            new_name='sale_date',
        ),
    ]
