# Generated by Django 5.0.3 on 2024-05-14 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0001_initial'),
        ('sales', '0003_rename_date_sale_sale_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='sale_date',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promos.promotion'),
        ),
    ]
