# Generated by Django 5.0.3 on 2024-05-16 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_date', models.DateTimeField(auto_now_add=True, verbose_name='buy date')),
                ('total', models.FloatField(verbose_name='total')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buys', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'buy',
                'verbose_name_plural': 'buys',
                'ordering': ['-buy_date'],
            },
        ),
        migrations.CreateModel(
            name='BuyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit price')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_buys', to='books.book')),
                ('buy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='buys.buy')),
            ],
            options={
                'verbose_name': 'Buy detail',
                'verbose_name_plural': 'Buy details',
                'ordering': ['-id'],
            },
        ),
    ]
