# Generated by Django 5.0.3 on 2024-05-06 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='total_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
