# Generated by Django 5.0.3 on 2024-05-09 19:44

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('description', models.TextField(help_text='A brief description of the promotion.', verbose_name='Description')),
                ('discount', models.FloatField(help_text='The percentage of discount to be applied to the book price.', validators=[django.core.validators.MinValueValidator(0, message='Discount must be greater than or equal to 0.'), django.core.validators.MaxValueValidator(100, message='Discount must be less than or equal to 100.')], verbose_name='Discount (%)')),
                ('start_date', models.DateTimeField(default=datetime.datetime.now, help_text='The date when the promotion starts being available.', verbose_name='Start date')),
                ('end_date', models.DateTimeField(default=datetime.datetime.now, help_text='The date when the promotion stops being available.', verbose_name='End date')),
                ('book', models.ManyToManyField(related_name='promotion', to='books.book', verbose_name='Book')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'ordering': ['name'],
            },
        ),
    ]
