# Generated by Django 5.0.3 on 2024-04-15 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_id_alter_book_barcode'),
        ('promos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='book',
            field=models.OneToOneField(default=283283, on_delete=django.db.models.deletion.CASCADE, related_name='promotion', to='books.book', verbose_name='Book'),
            preserve_default=False,
        ),
    ]
