# Generated by Django 5.0.3 on 2024-04-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_id_alter_book_barcode'),
        ('promos', '0002_promotion_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='book',
        ),
        migrations.AddField(
            model_name='promotion',
            name='book',
            field=models.ManyToManyField(related_name='promotion', to='books.book', verbose_name='Book'),
        ),
    ]
