# Generated by Django 5.0.3 on 2024-04-29 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0003_remove_promotion_book_promotion_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='The date when the promotion stops being available.', verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='The date when the promotion starts being available.', verbose_name='Start date'),
        ),
    ]
