# Generated by Django 5.0.3 on 2024-03-13 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pubdate',
        ),
    ]
