# Generated by Django 5.0.3 on 2024-04-18 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_id_alter_book_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='middle_name',
        ),
    ]
