# Generated by Django 5.0.3 on 2024-05-21 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='beneficiary',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
